In [1]:
import pandas as pd;

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
});

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
});

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees, departments, on = "DeptID") # Inner Join:-

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees, departments, on = "DeptID", how = "left") # Left Join:-

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees, departments, on = "DeptID", how = "right") # Right Join:-

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [9]:
pd.merge(employees, departments, on = "DeptID", how = "outer") # Outer Join:-

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [10]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]});
df2 = pd.DataFrame({"Name": ["Charlie", "David"]});

In [11]:
df1

    Name
0  Alice
1    Bob

In [12]:
df2

      Name
0  Charlie
1    David

In [13]:
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [14]:
pd.concat([df1, df2], axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [15]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "score": [423, 634]});
df2 = pd.DataFrame({"Name": ["Charlie", "Bob"], "age": [45, 78]});

In [16]:
df1

    Name  score
0  Alice    423
1    Bob    634

In [17]:
df2

      Name  age
0  Charlie   45
1      Bob   78

In [18]:
pd.concat([df1, df2])

      Name  score   age
0    Alice  423.0   NaN
1      Bob  634.0   NaN
0  Charlie    NaN  45.0
1      Bob    NaN  78.0

In [19]:
pd.concat([df1, df2], axis = 1)

    Name  score     Name  age
0  Alice    423  Charlie   45
1    Bob    634      Bob   78